name: React Native CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Build Android app
        run: npx react-native run-android --no-packager

      - name: Build iOS app
        run: npx react-native run-ios --no-packager

      - name: Run tests
        run: npm test
